/** The references, aggregated by category, for the pages that have no store list.
 *
 *  The drawer reads the pilot rows off the page it is opened from. That works inside the
 *  Pilots screen and gives nothing on `/help`, which is where the merchant link points.
 *
 *  Aggregated rather than a copy of the rows, and that is the design rather than a
 *  limitation: a link a merchant opens should not carry other merchants by name with their
 *  discounts and subscriber counts beside them. A category with its cadences, run lengths
 *  and discount band answers "what do stores like mine do" without answering "what does my
 *  competitor charge".
 *
 *  Uses the app's own parsers, so there is one reader of those cells and this cannot drift
 *  from what the drawer shows internally.
 *
 *  Run: npx tsx scripts/snapshot-references.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { byFrequency, parseDiscounts, parseFrequency } from "../lib/help/references";

const fx = JSON.parse(readFileSync(join(__dirname, "fixtures/pilot-plans.json"), "utf8"));

type Acc = { stores: number; every: number[]; runs: number[]; pct: number[] };
const by = new Map<string, Acc>();
for (const [cat, discount, freq] of fx.rows as [string, string, string][]) {
  const a = by.get(cat) || { stores: 0, every: [], runs: [], pct: [] };
  const f = parseFrequency(freq);
  a.stores++;
  a.every.push(...f.everyDays);
  a.runs.push(...f.deliveries);
  a.pct.push(...parseDiscounts(discount));
  by.set(cat, a);
}

const rows = [...by.entries()]
  .sort((x, y) => y[1].stores - x[1].stores || x[0].localeCompare(y[0]))
  .map(([label, a]) => {
    const p = [...a.pct].sort((m, n) => m - n);
    return {
      label, stores: a.stores,
      everyDays: byFrequency(a.every), deliveries: byFrequency(a.runs),
      discountLow: p[0] ?? null, discountHigh: p[p.length - 1] ?? null,
    };
  });

writeFileSync(join(__dirname, "../lib/help/reference-snapshot.ts"), `/** What our live stores run, by category, with no store named.
 *
 *  GENERATED by scripts/snapshot-references.ts from the live Pilots tab as read on the date
 *  below. Do not hand-edit: re-run the script when the sheet moves.
 *
 *  Aggregated on purpose. The drawer shows named store cards inside the Pilots screen, where
 *  the reader is us. This is what it shows on \`/help\` and on the merchant link, where the
 *  reader is a merchant and a list of other merchants with their discounts beside them is a
 *  commercial disclosure nobody agreed to. */

export interface ReferenceSnapshotRow {
  label: string;
  stores: number;
  /** Days between deliveries, most common first. */
  everyDays: number[];
  /** Run lengths sold in this category, most common first. */
  deliveries: number[];
  discountLow: number | null;
  discountHigh: number | null;
}

export const REFERENCE_SNAPSHOT_TAKEN = ${JSON.stringify(fx.read)};
export const REFERENCE_SNAPSHOT: ReferenceSnapshotRow[] = ${JSON.stringify(rows, null, 2)};
`);

console.log(`${rows.length} categories from ${fx.rows.length} live rows, as of ${fx.read}`);
for (const r of rows) {
  console.log(`  ${r.label.padEnd(44)} ${String(r.stores).padStart(2)} stores  `
    + `${r.everyDays.slice(0, 2).join("/") || "-"}d  ${r.deliveries.slice(0, 3).join(",") || "-"}  `
    + `${r.discountLow ?? "-"}-${r.discountHigh ?? "-"}%`);
}
