/** The references, aggregated by category, for the pages that have no store list.
 *
 *  The drawer reads the pilot rows off the page it is opened from. That works inside the
 *  Pilots screen and gives nothing on `/help`, which is where the merchant link points.
 *
 *  Aggregated rather than a copy of the rows, and that is the design rather than a
 *  limitation: a link a merchant opens should not carry other merchants by name with their
 *  discounts and subscriber counts beside them. A category with its cadences, run lengths
 *  and discount band answers "what do stores like mine do" without answering "what does my
 *  competitor charge".
 *
 *  Uses the app's own parsers, so there is one reader of those cells and this cannot drift
 *  from what the drawer shows internally.
 *
 *  Run: npx tsx scripts/snapshot-references.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { byFrequency, freqLabel, parseDiscounts, parseFrequency, parsePlans } from "../lib/help/references";

const fx = JSON.parse(readFileSync(join(__dirname, "fixtures/pilot-plans.json"), "utf8"));

interface Row {
  name: string; category: string; discountMargin: string; frequency: string;
  paymentType: string; shipping: string; bundles: string; themeNotes: string;
}

type Acc = { stores: Row[]; every: number[]; runs: number[]; pct: number[] };
const by = new Map<string, Acc>();
for (const r of fx.rows as Row[]) {
  const cat = (r.category || "").trim();
  if (!cat) continue;
  const a = by.get(cat) || { stores: [], every: [], runs: [], pct: [] };
  const f = parseFrequency(r.frequency);
  a.stores.push(r);
  a.every.push(...f.everyDays);
  a.runs.push(...f.deliveries);
  a.pct.push(...parseDiscounts(r.discountMargin));
  by.set(cat, a);
}

/** One store, as the drawer says it. Named, because Sumant asked for names on our own link
 *  and the public one does not render this list at all. Nothing here is a number that
 *  belongs to the store rather than to its plan shape: no subscriber counts, no contact, no
 *  activation state. */
const storeOf = (r: Row) => {
  const plans = parsePlans(r.frequency).flatMap((p) =>
    (p.everyDays.length ? p.everyDays : [0]).map((d) => ({
      cadence: d ? freqLabel(d) : null,
      deliveries: [...p.deliveries].sort((x, y) => x - y),
    })));
  const d = parseDiscounts(r.discountMargin);
  return {
    name: r.name,
    plans,
    discount: d.length ? Math.max(...d) : null,
    payment: r.paymentType || null,
    shipping: r.shipping || null,
    bundles: r.bundles || null,
  };
};

const rows = [...by.entries()]
  .sort((x, y) => y[1].stores.length - x[1].stores.length || x[0].localeCompare(y[0]))
  .map(([label, a]) => {
    const p = [...a.pct].sort((m, n) => m - n);
    const set = a.stores.filter((r) => parsePlans(r.frequency).length || parseDiscounts(r.discountMargin).length);
    return {
      label, stores: a.stores.length, withPlans: set.length,
      everyDays: byFrequency(a.every), deliveries: byFrequency(a.runs),
      discountLow: p[0] ?? null, discountHigh: p[p.length - 1] ?? null,
      /* Only the stores with something to show. A named store with every column blank tells
         a reader nothing and reads as a store that sells nothing. */
      named: set.map(storeOf),
    };
  });

writeFileSync(join(__dirname, "../lib/help/reference-snapshot.ts"), `/** What our live stores run, by category.
 *
 *  GENERATED by scripts/snapshot-references.ts from the live Pilots tab as read on the date
 *  below. Do not hand-edit: re-run \`npm run refs:snapshot\` when the sheet moves.
 *
 *  Carries store NAMES as well as the category aggregate, because the drawer renders them on
 *  our own surfaces and renders only the aggregate on the merchant link. What it does not
 *  carry is anything that belongs to the store rather than to its plan shape: no subscriber
 *  counts, no contact, no activation state, no open bugs. */

export interface ReferenceSnapshotStore {
  name: string;
  /** One entry per cadence the store sells, each with its OWN run lengths. */
  plans: { cadence: string | null; deliveries: number[] }[];
  discount: number | null;
  payment: string | null;
  shipping: string | null;
  bundles: string | null;
}

export interface ReferenceSnapshotRow {
  label: string;
  /** Every store in the category, including the ones with nothing logged. */
  stores: number;
  withPlans: number;
  /** Days between deliveries, most common first. */
  everyDays: number[];
  /** Run lengths sold in this category, most common first. */
  deliveries: number[];
  discountLow: number | null;
  discountHigh: number | null;
  named: ReferenceSnapshotStore[];
}

export const REFERENCE_SNAPSHOT_TAKEN = ${JSON.stringify(fx.read)};
export const REFERENCE_SNAPSHOT: ReferenceSnapshotRow[] = ${JSON.stringify(rows, null, 2)};
`);

console.log(`${rows.length} categories from ${fx.rows.length} live stores, as of ${fx.read}`);
for (const r of rows) {
  console.log(`  ${r.label.padEnd(44)} ${String(r.stores).padStart(2)} stores, ${String(r.withPlans).padStart(2)} with plans  `
    + `${r.everyDays.slice(0, 2).join("/") || "-"}d  ${r.deliveries.slice(0, 3).join(",") || "-"}  `
    + `${r.discountLow ?? "-"}-${r.discountHigh ?? "-"}%`);
}
