/** The plan configuration as a document, alongside the picture.
 *
 *  `sheet-png.ts` draws the same thing for a deck or a WhatsApp thread. This is for the
 *  half of the uses that are a paragraph in a reply or a line in a ticket: a picture cannot
 *  be searched, quoted, or diffed against the version you sent last week.
 *
 *  Walks `QUESTIONS` rather than naming fields, so a field added to the form appears here
 *  without anybody remembering to add it. Unanswered fields are listed rather than dropped:
 *  this downloads from a half-filled form on purpose, and a document that quietly omits what
 *  it does not know reads as a complete specification. */
import { QUESTIONS, parseBands, parseFreebies, parseList, visible, type Answers, type Field } from "./questions";
import { CATEGORIES } from "./categories";
import type { WidgetSettings } from "./widget";

const MODE_NAME: Record<string, string> = {
  prepaid: "Prepaid", payg: "Pay as you go", autopay: "AutoPay (UPI mandate)",
};

function shown(f: Field, a: Answers): string | null {
  const raw = a[f.id];
  const v = Array.isArray(raw) ? raw.filter(Boolean) : String(raw ?? "").trim();
  if (Array.isArray(v)) {
    if (!v.length) return null;
    return v.map((x) => f.options?.find((o) => o.value === x)?.label || MODE_NAME[x] || x).join(", ");
  }
  if (!v) return null;
  return f.options?.find((o) => o.value === v)?.label || v;
}

export function planDoc(a: Answers, brand: string, settings?: WidgetSettings): string {
  const L: string[] = [];
  const date = new Date().toISOString().slice(0, 10);
  L.push(`# ${brand || "Subscription plans"}`);
  L.push("", `StackBack subscription plans, as configured on ${date}.`, "");

  /* The plan ladder first, because it is the thing that gets argued about. */
  const runs = parseList(a.deliveries);
  const bands = parseBands(a.bands);
  const tiered = a.tiered === "yes";
  const flat = Number(a.discount_pct) || 0;
  if (runs.length) {
    L.push("## The plans", "", "| Run | Discount |", "|---|---|");
    for (const r of runs) L.push(`| ${r} deliveries | ${tiered ? (bands[r] ?? flat) : flat}% off |`);
    L.push("");
  }
  const gifts = parseFreebies(a.freebies);
  if (gifts.length) {
    L.push("**Freebies.** " + gifts
      .map((g) => `${g.product || "a gift"} on delivery ${g.delivery} of the ${g.run}-run`)
      .join("; ") + ".", "");
  }

  /* Then every answer, in the order the form asks for them. */
  const missing: string[] = [];
  for (const q of QUESTIONS) {
    const rows: string[] = [];
    for (const f of q.fields) {
      if (!visible(f, a)) continue;
      const v = shown(f, a);
      if (v) rows.push(`- **${f.label}:** ${v}`);
      else if (!f.optional) missing.push(`${q.title} › ${f.label}`);
    }
    if (rows.length) L.push(`## ${q.title}`, "", ...rows, "");
  }

  const cat = CATEGORIES.find((c) => c.id === String(a.category || ""));
  if (cat) {
    L.push("## Why this shape", "", cat.why, "",
      `Category default: every ${cat.everyDays.join(" or ")} days, ${cat.deliveries.join(", ")} deliveries, ${cat.discounts.join("/")}% off.`, "");
  }

  if (missing.length) {
    L.push("## Still to answer", "", ...missing.map((m) => `- ${m}`), "");
  }

  if (settings) {
    const t = settings.theme;
    L.push("## Widget", "",
      `- **Primary:** ${t.colors.primary}`,
      `- **Accent:** ${t.colors.subscriptionAccent}`,
      `- **Widget background:** ${t.surfaces.widgetBackground}`,
      `- **Corner radius:** ${t.shape.radius}px`,
      `- **Payment modes shown:** ${[
        settings.hide_prepaid ? null : "Prepaid",
        settings.hide_payg ? null : "Pay as you go",
        settings.hide_auto_debit ? null : "AutoPay",
      ].filter(Boolean).join(", ") || "none"}`, "");
  }

  L.push("---", "", "Generated by the StackBack Help Centre. Prices on the picture version are",
    "illustrative; this document carries the configuration only.");
  return L.join("\n");
}
