/** What our live stores run, by category, with no store named.
 *
 *  GENERATED by scripts/snapshot-references.ts from the live Pilots tab as read on the date
 *  below. Do not hand-edit: re-run the script when the sheet moves.
 *
 *  Aggregated on purpose. The drawer shows named store cards inside the Pilots screen, where
 *  the reader is us. This is what it shows on `/help` and on the merchant link, where the
 *  reader is a merchant and a list of other merchants with their discounts beside them is a
 *  commercial disclosure nobody agreed to. */

export interface ReferenceSnapshotRow {
  label: string;
  stores: number;
  /** Days between deliveries, most common first. */
  everyDays: number[];
  /** Run lengths sold in this category, most common first. */
  deliveries: number[];
  discountLow: number | null;
  discountHigh: number | null;
}

export const REFERENCE_SNAPSHOT_TAKEN = "2026-09-28";
export const REFERENCE_SNAPSHOT: ReferenceSnapshotRow[] = [
  {
    "label": "Protein & Supplement Brands",
    "stores": 12,
    "everyDays": [
      30,
      60,
      90
    ],
    "deliveries": [
      3,
      6,
      12,
      2,
      4,
      9
    ],
    "discountLow": 5,
    "discountHigh": 35
  },
  {
    "label": "Food & Grocery Brands",
    "stores": 11,
    "everyDays": [
      30,
      7,
      14
    ],
    "deliveries": [
      3,
      6,
      12,
      4,
      2,
      8
    ],
    "discountLow": 6,
    "discountHigh": 25
  },
  {
    "label": "Bath & Body Products",
    "stores": 5,
    "everyDays": [
      30,
      7
    ],
    "deliveries": [
      6,
      2,
      3,
      4,
      12
    ],
    "discountLow": 6,
    "discountHigh": 36
  },
  {
    "label": "Water, Juices, Kombucha & Bottled Beverages",
    "stores": 5,
    "everyDays": [
      7,
      30,
      14
    ],
    "deliveries": [
      6,
      3,
      12,
      9
    ],
    "discountLow": 7,
    "discountHigh": 20
  },
  {
    "label": "Coffee Brands",
    "stores": 2,
    "everyDays": [
      14,
      30,
      60
    ],
    "deliveries": [
      6,
      12,
      3,
      24,
      48
    ],
    "discountLow": 10,
    "discountHigh": 20
  },
  {
    "label": "Specialty Food & Snacks",
    "stores": 2,
    "everyDays": [
      30
    ],
    "deliveries": [
      3,
      6,
      12
    ],
    "discountLow": 10,
    "discountHigh": 15
  },
  {
    "label": "Tea Brands",
    "stores": 2,
    "everyDays": [
      14,
      30
    ],
    "deliveries": [
      3,
      6,
      12
    ],
    "discountLow": 10,
    "discountHigh": 20
  }
];
