/** What our live stores run, by category.
 *
 *  GENERATED by scripts/snapshot-references.ts from the live Pilots tab as read on the date
 *  below. Do not hand-edit: re-run `npm run refs:snapshot` when the sheet moves.
 *
 *  Carries store NAMES as well as the category aggregate, because the drawer renders them on
 *  our own surfaces and renders only the aggregate on the merchant link. What it does not
 *  carry is anything that belongs to the store rather than to its plan shape: no subscriber
 *  counts, no contact, no activation state, no open bugs. */

export interface ReferenceSnapshotStore {
  name: string;
  /** One entry per cadence the store sells, each with its OWN run lengths. */
  plans: { cadence: string | null; deliveries: number[] }[];
  discount: number | null;
  payment: string | null;
  shipping: string | null;
  bundles: string | null;
}

export interface ReferenceSnapshotRow {
  label: string;
  /** Every store in the category, including the ones with nothing logged. */
  stores: number;
  withPlans: number;
  /** Days between deliveries, most common first. */
  everyDays: number[];
  /** Run lengths sold in this category, most common first. */
  deliveries: number[];
  discountLow: number | null;
  discountHigh: number | null;
  named: ReferenceSnapshotStore[];
}

export const REFERENCE_SNAPSHOT_TAKEN = "2026-09-29";
export const REFERENCE_SNAPSHOT: ReferenceSnapshotRow[] = [
  {
    "label": "Food & Grocery Brands",
    "stores": 14,
    "withPlans": 10,
    "everyDays": [
      30,
      14,
      7
    ],
    "deliveries": [
      6,
      3,
      12,
      4,
      2,
      8
    ],
    "discountLow": 6,
    "discountHigh": 25,
    "named": [
      {
        "name": "MillD",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": []
          }
        ],
        "discount": 25,
        "payment": "Auto-Pay",
        "shipping": "60",
        "bundles": "No"
      },
      {
        "name": "Arusha Foods",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6
            ]
          }
        ],
        "discount": 15,
        "payment": "Both",
        "shipping": "Free",
        "bundles": "Yes"
      },
      {
        "name": "Yin N Yang",
        "plans": [
          {
            "cadence": "Weekly",
            "deliveries": [
              4,
              8
            ]
          },
          {
            "cadence": "Monthly",
            "deliveries": [
              3
            ]
          }
        ],
        "discount": 20,
        "payment": "Prepaid",
        "shipping": "99 - Maharashtra",
        "bundles": "Yes"
      },
      {
        "name": "Jab Marji",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              6
            ]
          }
        ],
        "discount": 6,
        "payment": "Both",
        "shipping": "35",
        "bundles": "No"
      },
      {
        "name": "Monks Bouffe",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6,
              12
            ]
          },
          {
            "cadence": "Fortnightly",
            "deliveries": [
              3,
              6,
              12
            ]
          }
        ],
        "discount": 15,
        "payment": "Prepaid",
        "shipping": "100rs below 999rs",
        "bundles": "Yes"
      },
      {
        "name": "Go Swasthya",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6
            ]
          }
        ],
        "discount": 15,
        "payment": "Both",
        "shipping": null,
        "bundles": "Yes"
      },
      {
        "name": "Millegram",
        "plans": [
          {
            "cadence": "Weekly",
            "deliveries": [
              6,
              12
            ]
          }
        ],
        "discount": 18,
        "payment": "Both",
        "shipping": "0",
        "bundles": "No"
      },
      {
        "name": "Orchard Lane",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              2,
              4,
              6
            ]
          }
        ],
        "discount": 15,
        "payment": "Both",
        "shipping": "Free",
        "bundles": "Yes"
      },
      {
        "name": "Rosier Foods",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6
            ]
          },
          {
            "cadence": "Fortnightly",
            "deliveries": [
              3,
              6,
              12
            ]
          }
        ],
        "discount": 20,
        "payment": "Prepaid",
        "shipping": "0",
        "bundles": "No"
      },
      {
        "name": "The Food RX Store",
        "plans": [
          {
            "cadence": "Fortnightly",
            "deliveries": [
              3,
              6,
              12
            ]
          }
        ],
        "discount": 10,
        "payment": "Prepaid",
        "shipping": "40rs below 400",
        "bundles": "No"
      }
    ]
  },
  {
    "label": "Protein & Supplement Brands",
    "stores": 14,
    "withPlans": 12,
    "everyDays": [
      30,
      7,
      60,
      90
    ],
    "deliveries": [
      3,
      6,
      12,
      2,
      4,
      9
    ],
    "discountLow": 8,
    "discountHigh": 36,
    "named": [
      {
        "name": "Everpure",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6,
              9
            ]
          }
        ],
        "discount": 25,
        "payment": "Prepaid",
        "shipping": "Free",
        "bundles": "No"
      },
      {
        "name": "The Basics Woman",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6,
              12
            ]
          }
        ],
        "discount": 20,
        "payment": "Both",
        "shipping": "Free",
        "bundles": "Yes"
      },
      {
        "name": "The Stack",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              6,
              12
            ]
          },
          {
            "cadence": "Every two months",
            "deliveries": [
              3,
              6
            ]
          },
          {
            "cadence": "Quarterly",
            "deliveries": [
              2,
              4
            ]
          }
        ],
        "discount": 35,
        "payment": "Prepaid",
        "shipping": "Free",
        "bundles": "Yes"
      },
      {
        "name": "The Func. Lab",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3
            ]
          }
        ],
        "discount": 8,
        "payment": "Prepaid",
        "shipping": "Free",
        "bundles": "Yes"
      },
      {
        "name": "NuFyt",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6,
              12
            ]
          }
        ],
        "discount": 12.52,
        "payment": "Prepaid",
        "shipping": "Free",
        "bundles": "No"
      },
      {
        "name": "Meru Activs",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6,
              12
            ]
          }
        ],
        "discount": 20,
        "payment": "Prepaid",
        "shipping": "20",
        "bundles": "Yes"
      },
      {
        "name": "Iron Asylum (Prosupps)",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              12
            ]
          }
        ],
        "discount": 20,
        "payment": "Prepaid",
        "shipping": "Free",
        "bundles": "No"
      },
      {
        "name": "SUPR",
        "plans": [
          {
            "cadence": "Weekly",
            "deliveries": [
              6,
              12
            ]
          },
          {
            "cadence": "Monthly",
            "deliveries": [
              6
            ]
          }
        ],
        "discount": 36,
        "payment": "Both",
        "shipping": "Free",
        "bundles": "Yes"
      },
      {
        "name": "Anvika Wellness",
        "plans": [
          {
            "cadence": null,
            "deliveries": [
              2,
              3,
              4
            ]
          }
        ],
        "discount": 15,
        "payment": "Prepaid",
        "shipping": "0",
        "bundles": "Yes"
      },
      {
        "name": "LightYearsHealth",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6,
              12
            ]
          }
        ],
        "discount": 15,
        "payment": "Prepaid",
        "shipping": "Free",
        "bundles": "No"
      },
      {
        "name": "Ace Blend",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6
            ]
          }
        ],
        "discount": 20,
        "payment": "Both",
        "shipping": "Free",
        "bundles": "Yes"
      },
      {
        "name": "Up&Run",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6
            ]
          }
        ],
        "discount": 15,
        "payment": "Both",
        "shipping": "Free",
        "bundles": "No"
      }
    ]
  },
  {
    "label": "Bath & Body Products",
    "stores": 7,
    "withPlans": 3,
    "everyDays": [
      30,
      7
    ],
    "deliveries": [
      3,
      6,
      12,
      2,
      4
    ],
    "discountLow": 6,
    "discountHigh": 25,
    "named": [
      {
        "name": "Dearist",
        "plans": [
          {
            "cadence": "Weekly",
            "deliveries": [
              2,
              4
            ]
          },
          {
            "cadence": "Monthly",
            "deliveries": [
              2
            ]
          }
        ],
        "discount": 6,
        "payment": "Prepaid",
        "shipping": "100 below 1000, Free over 1000",
        "bundles": "Yes"
      },
      {
        "name": "Hesthetics",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6,
              12
            ]
          }
        ],
        "discount": 12,
        "payment": "Both",
        "shipping": "Free",
        "bundles": "Yes"
      },
      {
        "name": "Origami Tissues",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6,
              12
            ]
          }
        ],
        "discount": 25,
        "payment": "Prepaid",
        "shipping": "0",
        "bundles": "Yes"
      }
    ]
  },
  {
    "label": "Water, Juices, Kombucha & Bottled Beverages",
    "stores": 5,
    "withPlans": 4,
    "everyDays": [
      7,
      30
    ],
    "deliveries": [
      3,
      6
    ],
    "discountLow": 5,
    "discountHigh": 20,
    "named": [
      {
        "name": "Tripitaka",
        "plans": [
          {
            "cadence": "Weekly",
            "deliveries": [
              3,
              6
            ]
          }
        ],
        "discount": 20,
        "payment": "Both",
        "shipping": "150",
        "bundles": "Yes"
      },
      {
        "name": "ActivHippy",
        "plans": [
          {
            "cadence": "Weekly",
            "deliveries": [
              3,
              6
            ]
          },
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6
            ]
          }
        ],
        "discount": 20,
        "payment": "Both",
        "shipping": "0",
        "bundles": "Yes"
      },
      {
        "name": "BLND",
        "plans": [
          {
            "cadence": "Weekly",
            "deliveries": [
              6
            ]
          },
          {
            "cadence": "Monthly",
            "deliveries": [
              3
            ]
          }
        ],
        "discount": 7,
        "payment": "Prepaid",
        "shipping": "0",
        "bundles": "Yes"
      },
      {
        "name": "Local Ferment .Co",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6
            ]
          }
        ],
        "discount": 5,
        "payment": "Prepaid",
        "shipping": "Free",
        "bundles": "No"
      }
    ]
  },
  {
    "label": "Coffee Brands",
    "stores": 4,
    "withPlans": 3,
    "everyDays": [
      30,
      14,
      7,
      60
    ],
    "deliveries": [
      6,
      12,
      3,
      9,
      24,
      48
    ],
    "discountLow": 10,
    "discountHigh": 12.5,
    "named": [
      {
        "name": "Boojee",
        "plans": [
          {
            "cadence": "Fortnightly",
            "deliveries": [
              24,
              48
            ]
          },
          {
            "cadence": "Monthly",
            "deliveries": [
              6,
              12
            ]
          },
          {
            "cadence": "Every two months",
            "deliveries": [
              6,
              12
            ]
          }
        ],
        "discount": 10,
        "payment": "Prepaid",
        "shipping": "100 below 1000, Free over 1000",
        "bundles": "No"
      },
      {
        "name": "Nice Guys Coffee",
        "plans": [
          {
            "cadence": "Weekly",
            "deliveries": [
              3,
              6,
              9,
              12
            ]
          },
          {
            "cadence": "Fortnightly",
            "deliveries": [
              3,
              6,
              9,
              12
            ]
          },
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6,
              9,
              12
            ]
          }
        ],
        "discount": 12.5,
        "payment": "Prepaid",
        "shipping": "Free",
        "bundles": "Yes"
      },
      {
        "name": "G-Shot Coffee",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": []
          }
        ],
        "discount": 10,
        "payment": "PAYG",
        "shipping": "Free",
        "bundles": "No"
      }
    ]
  },
  {
    "label": "Specialty Food & Snacks",
    "stores": 3,
    "withPlans": 1,
    "everyDays": [
      30
    ],
    "deliveries": [
      3,
      6
    ],
    "discountLow": 15,
    "discountHigh": 15,
    "named": [
      {
        "name": "Mittai Kadai",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6
            ]
          }
        ],
        "discount": 15,
        "payment": "Both",
        "shipping": "Free",
        "bundles": "Yes"
      }
    ]
  },
  {
    "label": "Female Hygiene Products",
    "stores": 2,
    "withPlans": 2,
    "everyDays": [
      30
    ],
    "deliveries": [
      3,
      6,
      12
    ],
    "discountLow": 10,
    "discountHigh": 15,
    "named": [
      {
        "name": "Zoy Care",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6,
              12
            ]
          }
        ],
        "discount": 10,
        "payment": "Auto-Pay",
        "shipping": "Free",
        "bundles": "Yes"
      },
      {
        "name": "Avni Wellness",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6
            ]
          }
        ],
        "discount": 15,
        "payment": "Both",
        "shipping": "Free",
        "bundles": "Yes"
      }
    ]
  },
  {
    "label": "Tea Brands",
    "stores": 2,
    "withPlans": 2,
    "everyDays": [
      30
    ],
    "deliveries": [
      3,
      6
    ],
    "discountLow": 15,
    "discountHigh": 20,
    "named": [
      {
        "name": "Glow Glossary",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3,
              6
            ]
          }
        ],
        "discount": 20,
        "payment": "Both",
        "shipping": "Free",
        "bundles": "Yes"
      },
      {
        "name": "BlueTea",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              3
            ]
          }
        ],
        "discount": 15,
        "payment": "Prepaid",
        "shipping": "Free",
        "bundles": "No"
      }
    ]
  },
  {
    "label": "Pet Food & Supplies",
    "stores": 1,
    "withPlans": 1,
    "everyDays": [
      30
    ],
    "deliveries": [
      2,
      3,
      4
    ],
    "discountLow": 25,
    "discountHigh": 25,
    "named": [
      {
        "name": "Honest Pet Co.",
        "plans": [
          {
            "cadence": "Monthly",
            "deliveries": [
              2,
              3,
              4
            ]
          }
        ],
        "discount": 25,
        "payment": "Both",
        "shipping": "0",
        "bundles": "Yes"
      }
    ]
  }
];
